"
This class uses BaselineOf to create an RSBaselineModel, used to create the visualization
"
Class {
	#name : #ManifestRoassal3UML,
	#superclass : #PackageManifest,
	#category : #'Roassal3-UML-Manifest'
}

{ #category : #'code-critics' }
ManifestRoassal3UML class >> ruleEndTrueFalseRuleV1FalsePositive [
	^ #(#(#(#RGMethodDefinition #(#RSUMLSequenceDescriptor #cumulateWidths #false)) #'2021-12-20T16:40:22.07811+01:00') )
]
