"
I return the linear interpolation
"
Class {
	#name : #RSLinearInterpolator,
	#superclass : #NSInterpolator,
	#category : #'Roassal3-Animation-Easing'
}

{ #category : #modes }
RSLinearInterpolator >> in [
]

{ #category : #modes }
RSLinearInterpolator >> inOut [
]

{ #category : #interpolation }
RSLinearInterpolator >> interpolate: aNumber [
	^ aNumber
]

{ #category : #modes }
RSLinearInterpolator >> out [
]
