# This is a basic workflow to help you get started with Actions

name: SmallAmpCI


env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  reponame: ${{github.event.repository.name}}


# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        portion: [0,1,2,3,4,5,6,7,8,9]
    name: Job number ${{ strategy.job-index }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-version: Pharo64-9.0
      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-version }}
        shell: bash
        timeout-minutes: 15
      - uses: mabdi/smallamp-action@main
      - run: smallAmpCI
        shell: bash    
        env:
          # you can also use: ${{ matrix.portion }}
          SMALLAMP_PORTION: ${{ strategy.job-index }} 
          SMALLAMP_ALLJOBS: ${{ strategy.job-total }}
